### ISSUE TITLE
DevicesApi.GetDevices throws an exception

### ISSUE THREAD

**Issue by rboy1** [daltskin/SmartThingsNet#16]
Using SmartThingsTerminal, tracing down the root cause of an error message when trying to enumerate devices in `ApiClient.cs` at line 129
> SmartThingsNet.Client.ApiException
  HResult=0x80131500
  Message=Error converting value "ZIGBEE" to type 'System.Nullable`1[SmartThingsNet.Model.DeviceIntegrationType]'. Path 'items[97].type', line 1, position 131833.
  Source=SmartThingsNet
  StackTrace:
   at SmartThingsNet.Client.CustomJsonCodec.Deserialize(IRestResponse response, Type type) in C:\Users\R\Desktop\SmartThingsTerminal-master\SmartThingsNet\Client\ApiClient.cs:line 134
   at SmartThingsNet.Client.CustomJsonCodec.Deserialize[T](IRestResponse response) in C:\Users\R\Desktop\SmartThingsTerminal-master\SmartThingsNet\Client\ApiClient.cs:line 74
   at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)

It looks like it's having trouble while trying to deserialize the device information (which I can see is a valid JSON being returned by the platform)

**Comment by rboy1** [comment]
There are some new device types defined by the ST API's which aren't part of the current SDK
> "WATCH" "GROUP" "LAN" "ZIGBEE" "ZWAVE" "MATTER"

https://developer-preview.smartthings.com/api/public#operation/getDevices

**Comment by daltskin** [comment]
Thanks for raising - have regenerated and updated.
