### ISSUE TITLE
GetDevices API returns an exception, does not support EDGE_CHILD

### ISSUE THREAD

**Issue by rboy1** [daltskin/SmartThingsNet#21]
This is also causing SmartThings Terminal to throw an exception while enumerating devices

```
SmartThingsNet.Client.ApiException
  HResult=0x80131500
  Message=Error converting value "EDGE_CHILD" to type 'SmartThingsNet.Model.DeviceIntegrationType'. Path 'items[0].type', line 1, position 885.
  Source=SmartThingsNet
  StackTrace:
   at SmartThingsNet.Client.CustomJsonCodec.Deserialize(IRestResponse response, Type type) in SmartThingsNet-master\src\Client\ApiClient.cs:line 145
   at SmartThingsNet.Client.CustomJsonCodec.Deserialize[T](IRestResponse response) in SmartThingsNet-master\src\Client\ApiClient.cs:line 86
   at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)
```

**Comment by rboy1** [comment]
https://github.com/daltskin/SmartThingsNet/pull/22

**Comment by daltskin** [comment]
Thanks @rboy1 I've migrated to Home Assistant so not using this much now - but thanks for the contribution :)

Latest package includes your fix so if this resolves the above lmk and I'll close this out
